### ISSUE TITLE
Montoyo Website down

### ISSUE THREAD

**Issue by Yanniclord** [montoyo/mcef#14]
Main website is down, hence MCEF and JCEF do not work.

https://montoyo.net/jcef.

**Comment by spannerman79** [comment]
Your end

http://www.isitdownrightnow.com/montoyo.net.html

**Comment by Yanniclord** [comment]
No, its not. Add the . that is at the end of the URL, the link i posted works, but not with the ., and that is where it gets the files from, which it can't. It doesn't work for anyone of my friends, and if you check the MCEF thread, someone else has the same problem for 1.8.

**Comment by Yanniclord** [comment]
The directory works, but with the dot (.) at the end (which GitHub is to stupid to add properly), it does not work, and that is what it is configured to in the config file.

**Comment by Yanniclord** [comment]
Changing it to without the dot, does nothing. The dot basically tells that there is something there, like some special directory for downloading from Apache, but that does not work.

**Comment by Yanniclord** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2324969-minecraft-chromium-embedded-framework-mcef?page=6#c116

**Comment by spannerman79** [comment]
https://github.com/montoyo/mcef/blob/master/java/net/montoyo/mcef/remote/Mirror.java#L21

**Comment by Yanniclord** [comment]
Ye what about it? It still does not work, removing the dot or not. I can see in my web browser, the page i linked to, but MINECRAFT does not understand that it should download the required files from there, and as of that it does not work, NOT just for me.

**Comment by Yanniclord** [comment]
We are using v0.6, 0.7 crashes with Web Displays.

**Comment by Yanniclord** [comment]
Again, version 0.6, no idea if it is fixed there with the mirror stuff you mentioned, but what do i have to put into the forced mirror link field then? I put in that exact address, still does not work. Minecraft is not downloading the files it should download from the link specified in the java file you quoted.

**Comment by Yanniclord** [comment]
I decompiled the Mirror.class in version 0.6, and got this: http://pastebin.com/Pu0Q0Uk3

Seems to be the same, but why doesn't Minecraft understand that? It worked some days ago, and it suddenly stopped working for all my friends, in the US, Norway, Germany, everywhere. The JCEF process does not start, and we get this error:

[14:38:35] [Client thread/INFO] [MCEF/MCEF]: Now initializing MCEF v0.6...
[14:38:36] [Client thread/ERROR] [MCEF/MCEF]: Syntax error in remote config.
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.gson.JsonParser.parse(JsonParser.java:65)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.montoyo.mcef.remote.RemoteConfig.readConfig(RemoteConfig.java:49)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.montoyo.mcef.remote.RemoteConfig.readConfig(RemoteConfig.java:80)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.montoyo.mcef.remote.RemoteConfig.load(RemoteConfig.java:97)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.montoyo.mcef.client.ClientProxy.onInit(ClientProxy.java:59)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.montoyo.mcef.MCEF.onInit(MCEF.java:44)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 2
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1505)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1386)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:531)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.gson.stream.JsonReader.peek(JsonReader.java:414)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at com.google.gson.JsonParser.parse(JsonParser.java:60)
[14:38:36] [Client thread/INFO] [STDERR/MCEF]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	... 41 more
[14:38:36] [Client thread/ERROR] [MCEF/MCEF]: Could NOT read either remote and local configuration files. Entering virtual mode.
[14:38:36] [Client thread/INFO] [MCEF/MCEF]: Checking for missing resources...
[14:38:36] [Client thread/INFO] [MCEF/MCEF]: None are missing. Good.
[14:38:36] [Client thread/TRACE] [MCEF/MCEF]: Sent event FMLInitializationEvent to mod MCEF

**Comment by Yanniclord** [comment]
I switched to the mirror i am hosting myself, and i still get this:

http://pastebin.com/L6bPRzT3

There seems to be something wrong with the config file (the JSON one), but what?

**Comment by Yanniclord** [comment]
This is the config:

http://pastebin.com/1G12yXfY

What is wrong with it in line 2 column 2?

**Comment by montoyo** [comment]
Maybe it's because montoyo.net recently switched to HTTPS. However, HTTP requests should still work as they are redirected. Can't do anything right now since I'm not at home.

**Comment by montoyo** [comment]
You can still try to edit your config to use HTTPS, just like this:
forcedMirror=https://montoyo.net/jcef

**Comment by Yanniclord** [comment]
Will do, thank you.

**Comment by Yanniclord** [comment]
Well the problem is that is gives out some kind of problem with the config.

**Comment by montoyo** [comment]
It's not. The JSON Parser is actually reading HTML (saying that content was moved permanently) and thus erroring.
I just made SSL optional again, can you give it a try? Thanks.

**Comment by spannerman79** [comment]
@montoyo Perhaps change https://github.com/montoyo/mcef/blob/master/java/net/montoyo/mcef/remote/Mirror.java#L21 to be `MONTOYO("//montoyo.net/jcef", "montoyo.net");` that way it wouldn't matter for http/https (works for CSS, not 100% sure about java)

**Comment by montoyo** [comment]
@spannerman79 Will try it; thanks.
@Yanniclord works well for me; is it fixed for you too?

**Comment by Yanniclord** [comment]
Will check, have to reboot the server and client, do that in 10 min or so.

**Comment by quentfr21** [comment]
bonjour

pour ma part tout fonctionne à nouveau y compris le telechargement automatique des librairies

merci

**Comment by Yanniclord** [comment]
English? You don't help yourself by speaking french, but i think Montoyo speaks french, luckily for you.
