### ISSUE TITLE
Can't use screen

### ISSUE THREAD

**Issue by MPeti1** [montoyo/mcef#24]
Hi!
If i build a screen and right click on it, the screen becomes grey, and i can do nothing with it.
I use Web Displays 0.11 and MCEF 0.6.
I noticed when i assemble a screen (when i first turn it on) it dumps an error to console:
 `Creating webview!
[18:11:19] [Thread-34/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NoClassDefFoundError: org/cef/handler/CefFocusHandler$FocusSource
[18:11:19] [Thread-34/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: Caused by: java.lang.ClassNotFoundException: org.cef.handler.CefFocusHandler$FocusSource
[18:11:19] [Thread-34/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[18:11:19] [Thread-34/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:11:19] [Thread-34/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
[18:11:19] [Thread-34/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
`
What is the problem?
![kep](https://cloud.githubusercontent.com/assets/9215491/26522775/6da0ead2-4308-11e7-9bc9-ef9134b04bb0.png)

**Comment by spannerman79** [comment]
need full fml log - put the log onto gist

**Comment by MPeti1** [comment]
[here ](https://gist.github.com/MPeti1/c8dd7966bfcdfb2ce9c9c2d1bcaae7fc)is it.

**Comment by spannerman79** [comment]
Test using MultiMC

**Comment by spannerman79** [comment]
I just did a fresh instance in MultiMC

https://paste.ee/p/JOARs

![2017-05-28_11 43 36](https://cloud.githubusercontent.com/assets/7542384/26525477/63e73c4c-439b-11e7-8319-af1585d75f64.png)

Seems to work without any issues.

**Comment by MPeti1** [comment]
Same here
![kep](https://cloud.githubusercontent.com/assets/9215491/26528022/317fb85a-43a1-11e7-81da-cf0441dcdc61.png)

**Comment by spannerman79** [comment]
You didn't load up a URL to test like I did.  So no, you didn't test properly nor fully.

**Comment by MPeti1** [comment]
i can't write any url to the screen
yes, i've succesfully connected the keyboard to the screen

**Comment by spannerman79** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291044-web-displays-browse-on-the-internet-in-minecraft

> Then, build a little walll with them (minimum size: 2x2) and right click on the side where you want the screen to appear (check that you don't have any items in your hand). That's it, you created your screen. **Shift-Right Click to change the URL**. To click on a link/button, simply right-click it with nothing in the hand.

Next time read the OP

**Comment by MPeti1** [comment]
oh, really :D sorry, my fault. I'm trying to resolve bugs in 3 mods at a time, i promise i've read the description in minecraftforum, it's just a bit hard to remember everything :D

**Comment by spannerman79** [comment]
Then in that case close this issue.  Don't leave open issues when your issue is resolved.

This applies across Github and any other issue tracker system.
