### ISSUE TITLE
It keeps crashing

### ISSUE THREAD

**Issue by TheLionWarlord** [montoyo/mcef#35]
I have downloaded Webdisplays and mcef, and every time I try to launch minecraft, it crashes. I have taken out other mods I had, and it still crashes. Could I please get some help?

**Comment by spannerman79** [comment]
Log or it never happened
Use gist or pastebin/paste.ee etc

**Comment by TheLionWarlord** [comment]
Is this what you wanted?

The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WebDisplays (webdisplays)




---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 9/3/18 12:32 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from WebDisplays (webdisplays)
Caused by: java.lang.IllegalAccessError: tried to access method net.minecraft.advancements.CriteriaTriggers.func_192118_a(Lnet/minecraft/advancements/ICriterionTrigger;)Lnet/minecraft/advancements/ICriterionTrigger; from class net.montoyo.wd.WebDisplays
	at net.montoyo.wd.WebDisplays.registerTrigger(WebDisplays.java:410)
	at net.montoyo.wd.WebDisplays.onPreInit(WebDisplays.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1463559024 bytes (1395 MB) / 3053453312 bytes (2912 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2556 Optifine OptiFine_1.12.2_HD_U_E2 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version      | Source                         | Signature                                |
	|:----- |:----------------- |:------------ |:------------------------------ |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2       | minecraft.jar                  | None                                     |
	| UCH   | mcp               | 9.42         | minecraft.jar                  | None                                     |
	| UCH   | FML               | 8.0.99.99    | forge-1.12.2-14.23.1.2556.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.1.2556 | forge-1.12.2-14.23.1.2556.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | obfuscate         | 0.2.5        | minecraft.jar                  | None                                     |
	| UCH   | mercurius_updater | 1.0          | MercuriusUpdater-1.12.2.jar    | None                                     |
	| UCH   | cdm               | 0.4.1        | cdm-0.4.1-mc1.12.2 (1).jar     | None                                     |
	| UCH   | cfm               | 5.8.0        | cfm-5.8.0-mc1.12.2.jar         | None                                     |
	| UCH   | ptrmodellib       | 1.0.2        | PTRLib-1.0.2.jar               | None                                     |
	| UCH   | props             | 2.6.1        | Decocraft-2.6.1_1.12.2.jar     | None                                     |
	| UCH   | malisiscore       | 1.12.2-6.4.0 | malisiscore-1.12.2-6.4.0.jar   | None                                     |
	| UCH   | malisisdoors      | 1.12.2-7.3.0 | malisisdoors-1.12.2-7.3.0.jar  | None                                     |
	| UCH   | mcef              | 0.9          | mcef-1.12.2-0.9 (3).jar        | None                                     |
	| UCH   | harvestcraft      | 1.12.2u      | Pam's+HarvestCraft+1.12.2v.jar | None                                     |
	| UCH   | vehicle           | 0.21.0       | vehicle-0.21.0-mc1.12.2.jar    | None                                     |
	| UCE   | webdisplays       | 1.0          | webdisplays-1.12.2-1.0 (4).jar | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
ObfuscatePlugin (obfuscate-0.2.5-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	OptiFine Version: OptiFine_1.12.2_HD_U_E2
	OptiFine Build: 20180728-185429
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 398.36
	OpenGlRenderer: GeForce GTX 960M/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by spannerman79** [comment]
https://github.com/montoyo/mcef/issues/15#issuecomment-408388491

**Comment by TheLionWarlord** [comment]
What do you mean? I don’t get it.

**Comment by TheLionWarlord** [comment]
The game crashes while it is trying to load the game.

**Comment by montoyo** [comment]
That's probably due to a bad forge version. Try with forge 14.23.2.2611

**Comment by Dface-crypto** [comment]
I have the same problem as TheLionWarlord. Please help. I'm developing a virtual concert venue in Minecraft for a charity event on 8 May and Web Display is the only way I can see to stream the concert in the virtual venue. I have installed forge 14.23.2.2611 as well as the latest version of forge with the same crash (full crash report attached).
[crash-2020-04-26_18.53.16-client.txt](https://github.com/montoyo/mcef/files/4536115/crash-2020-04-26_18.53.16-client.txt)
